"""Add system view_audit_logs permission

Revision ID: 4a222b228f68
Revises: 562bb0accbbf
Create Date: 2026-03-29 22:50:03.477664
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a222b228f68'
down_revision = '562bb0accbbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get IDs for permission and admin role
    # Note: Use existing names to find IDs if possible, or just generate new ones for the permission
    import uuid
    permission_id = uuid.uuid4()
    
    # 1. Insert the permission
    op.execute(
        sa.text(
            "INSERT INTO permissions (id, code, description, created_at) "
            "VALUES (:id, :code, :description, NOW())"
        ).bindparams(
            id=permission_id,
            code="system.view_audit_logs",
            description="View system audit logs and events."
        )
    )
    
    # 2. Assign to admin role (assuming 'admin' exists)
    op.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT id, :permission_id FROM roles WHERE name = 'admin'"
        ).bindparams(permission_id=permission_id)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = 'system.view_audit_logs')"
        )
    )
    op.execute(
        sa.text("DELETE FROM permissions WHERE code = 'system.view_audit_logs'")
    )
    # ### end Alembic commands ###
