"""Rename metadata_json to context

Revision ID: 562bb0accbbf
Revises: 4b0b6d10c336
Create Date: 2026-03-29 22:35:46.143805
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '562bb0accbbf'
down_revision = '4b0b6d10c336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'metadata_json', new_column_name='context')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'context', new_column_name='metadata_json')
    # ### end Alembic commands ###
