"""add_deleted_at_to_chat_session

Revision ID: 5f612943e644
Revises: 20260327_0004
Create Date: 2026-03-28 19:26:13.371642
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f612943e644'
down_revision = '20260327_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'deleted_at')
    # ### end Alembic commands ###
