#!/bin/bash

# ═══════════════════════════════════════════════════════════════════════
# CLEO Infrastructure Deployment - Quick Reference
# ═══════════════════════════════════════════════════════════════════════

echo "╔════════════════════════════════════════════════════════════╗"
echo "║           CLEO Azure Infrastructure - Quick Deploy         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Follow these steps to deploy CLEO on Azure:"
echo ""
echo "1️⃣  LOGIN TO AZURE"
echo "   az login"
echo "   az account set --subscription \"0d5505db-c5a0-4a2d-8e52-1ff49cd01a36\""
echo ""
echo "2️⃣  GENERATE SSH KEY (if you don't have one)"
echo "   ssh-keygen -t rsa -b 4096 -f ~/.ssh/cleo-azure"
echo ""
echo "3️⃣  CREATE SERVICE PRINCIPAL"
echo "   cd infrastructure/terraform"
echo "   chmod +x setup-service-principal.sh"
echo "   ./setup-service-principal.sh"
echo "   # Save the output credentials!"
echo ""
echo "4️⃣  CONFIGURE TERRAFORM"
echo "   cp terraform.tfvars.example terraform.tfvars"
echo "   nano terraform.tfvars  # Edit with your credentials"
echo ""
echo "5️⃣  DEPLOY INFRASTRUCTURE"
echo "   terraform init"
echo "   terraform plan"
echo "   terraform apply"
echo ""
echo "6️⃣  GET CONNECTION INFO"
echo "   terraform output vm_public_ip"
echo "   terraform output ssh_connection_string"
echo ""
echo "7️⃣  CONNECT TO VM"
echo "   ssh -i ~/.ssh/cleo-azure azureuser@<VM_IP>"
echo ""
echo "8️⃣  DEPLOY APPLICATION"
echo "   cd /opt/cleo"
echo "   git clone <your-repo-url> ."
echo "   # Configure .env files"
echo "   docker-compose up -d"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📚 For detailed instructions, see:"
echo "   infrastructure/terraform/README.md"
echo "═══════════════════════════════════════════════════════════"
echo ""
